name: Knitting wool web scraper
on:
  push:
  pull_request:

jobs:
  code_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: which python
      - run: python --version
      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install black
          black ./
          rm -rf venv

  tests:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: which python
       - run: python --version
       - run: |
           python -m venv venv
           source venv/bin/activate
           pip install -e .
           pytest
           rm -rf venv

